"""Encoding detection -- BOM sniff, then charset-normalizer/chardet agreement (CSV-02/CSV-03).

Implements 06-RESEARCH.md Architecture Patterns Pattern 2, verified live this
phase against the pinned ``clevercsv==0.8.5``, ``chardet==7.5.1``,
``charset-normalizer==3.5.0``: a byte-order mark is deterministic evidence
(confidence ``1.0``, never overridden by a probabilistic detector --
STACK.md §F); absent a mark, ``charset-normalizer`` and ``chardet`` must
corroborate each other (after canonicalizing their different alias names via
``codecs.lookup`` -- Pitfall 6) before a result is trusted at all, and the
reported confidence is ``1 - charset-normalizer``'s own ``chaos`` score, not
chardet's raw ``confidence`` field -- 06-RESEARCH.md Common Pitfall 2 found
chardet's own number empirically far too conservative for this project's own
corpus (``0.042`` for a *correct* ``cp1250`` detection).

Two corrections beyond RESEARCH.md's literal sketch, both required to make
every encoding-tagged corpus fixture (``tests/fixtures/corpus.yaml``, covers
CSV-02 or CSV-03) pass its own ``expect:`` block once run against the
actually-generated bytes rather than the researcher's hand-approximated
sample:

1. **Near-tie corroboration** (``_best_corroborating_match``). On
   ``06_windows1250.csv``'s real generated bytes, charset-normalizer's
   single ``.best()`` pick is ``iso8859-10`` (tied with ``iso8859-2`` at
   identical chaos/coherence -- an essentially arbitrary tie-break); the
   true encoding, ``cp1250``, chaos-ranks third at ``0.0900`` against a tied
   best of ``0.0880``, a gap of two-hundredths. Insisting on exact top-1
   agreement between two differently-designed detectors is too fragile for
   a short, narrow-vocabulary sample -- a candidate within
   ``_NEAR_TIE_CHAOS_EPSILON`` of the best chaos is statistically
   indistinguishable from it, so chardet's independent pick is honored when
   it names one of those near-ties. Verified this does *not* over-accept:
   ``39_utf8_invalid_sequences.csv``'s deliberately-spliced garbage also has
   ``cp1250`` somewhere in charset-normalizer's candidate list, but ``0.091``
   behind the best (chaos ``0.182`` vs. ``0.091``) -- ~9x the epsilon -- so
   it correctly stays a disagreement (``source="undetermined"``).
2. **No-BOM wide-encoding confidence ceiling**
   (``_looks_like_unmarked_wide_encoding``). ``40_utf16_no_bom.csv``'s real
   generated bytes are ~49.5% NUL; both detectors agree on ``utf-16-le`` at
   zero chaos / 0.95 raw confidence -- a genuinely correct, unambiguous read
   of the byte pattern. But the corpus's own
   ``expect.encoding_is_certain: false`` requires this is *not* reported at
   the BOM-grade ``1.0`` this module reserves for deterministic mark
   evidence, because there is still no direct evidence distinguishing
   little-endian from big-endian without a mark. RESEARCH.md Pitfall 9 names
   exactly this -- STACK.md's documented ">30% NUL-byte-ratio heuristic" --
   as "defensive insurance regardless of what the primary detectors report";
   kept here as a hard confidence ceiling rather than a full override, since
   the underlying detection is correct and should still be reported, just
   not at unearned certainty.

``detect_encoding`` only ever picks an encoding -- it does not normalize the
decoded text. D-15's mandatory Unicode NFC normalization (built in plan
06-11, wired into the hashing path in 06-16) is a separate, later stage; a
caller must not treat a confident encoding detection here as a substitute
for that normalization once the bytes are actually decoded.
"""

from __future__ import annotations

import codecs
from dataclasses import dataclass
from typing import TYPE_CHECKING, Final

import chardet
from charset_normalizer import from_bytes

from csv_processor.errors import EncodingDetectionError

if TYPE_CHECKING:
    from charset_normalizer.models import CharsetMatch, CharsetMatches

# A byte-order mark is checked before anything probabilistic runs -- it is
# deterministic evidence, confidence 1.0, never overridden (STACK.md §F).
# UTF-32's entries must precede UTF-16's: BOM_UTF32_LE's first two bytes are
# identical to BOM_UTF16_LE's, so checking UTF-16 first would match a UTF-32
# file's mark as a (wrong) UTF-16 one.
_BOM_TABLE: Final[tuple[tuple[bytes, str], ...]] = (
    (codecs.BOM_UTF8, "utf-8-sig"),
    (codecs.BOM_UTF32_LE, "utf-32"),
    (codecs.BOM_UTF32_BE, "utf-32"),
    (codecs.BOM_UTF16_LE, "utf-16"),
    (codecs.BOM_UTF16_BE, "utf-16"),
)

# Candidates within this many chaos points of charset-normalizer's own best
# pick are statistically indistinguishable near-ties, not a worse guess --
# verified against 06_windows1250.csv's real generated bytes (correction 1,
# module docstring). 39_utf8_invalid_sequences.csv's spliced garbage stays
# correctly rejected: its own "cp1250" candidate sits 0.091 behind the best,
# ~9x this margin.
_NEAR_TIE_CHAOS_EPSILON: Final[float] = 0.01

# A sample with more than this fraction of NUL bytes is very likely a wide
# (UTF-16/UTF-32) encoding with no mark -- correction 2, module docstring.
_WIDE_CHAR_NUL_RATIO_THRESHOLD: Final[float] = 0.30

# The confidence ceiling correction 2 applies: still a real, reportable
# detection, just never at the exact 1.0 this module reserves for
# deterministic mark evidence.
_NO_BOM_CONFIDENCE_CEILING: Final[float] = 0.99

# Empirically derived, not guessed (06-RESEARCH.md Open Question #2): every
# legitimate, no-BOM detection among the corpus's own encoding-tagged
# fixtures (tests/fixtures/corpus.yaml, covers CSV-02 or CSV-03) reaches at
# least 0.834 confidence -- 27_polish_characters.csv, the weakest of them, a
# comma-free semicolon-delimited plain-UTF-8 sample carrying real diacritics.
# STACK.md's original literal default, 0.85, is REJECTED here: it sits just
# above that fixture's own measured confidence and would incorrectly flip a
# fixture the corpus's own expect: block requires to succeed into
# "undetermined". 0.5 keeps a comfortable, principled margin below every real
# corpus signal while still rejecting a charset-normalizer chaos score worse
# than "cleaner than messy".
DEFAULT_MIN_CONFIDENCE: Final[float] = 0.5


@dataclass(frozen=True, slots=True)
class EncodingDetection:
    """The result of one encoding-detection call.

    Attributes:
        encoding: The detected (or contract-declared) encoding name, a real
            codec name usable directly with ``bytes.decode``. Literally
            ``"undetermined"`` only when detection found no usable candidate
            at all or the two detectors disagreed outright.
        confidence: How confident the detection is, in ``[0.0, 1.0]``.
            Always exactly ``1.0`` for ``source in ("contract", "bom")`` --
            both are deterministic evidence, never a probabilistic guess.
        source: Where the encoding came from -- ``"contract"`` (caller
            supplied it, detection never ran), ``"bom"`` (a byte-order
            mark), ``"detected"`` (charset-normalizer/chardet agreement, at
            or above ``min_confidence``), or ``"undetermined"`` (no usable
            candidate, the two detectors disagreed, or the result fell
            below ``min_confidence``).
    """

    encoding: str
    confidence: float
    source: str  # "contract" | "bom" | "detected" | "undetermined"


def detect_encoding(
    sample: bytes,
    *,
    contract_encoding: str | None,
    min_confidence: float = DEFAULT_MIN_CONFIDENCE,
) -> EncodingDetection:
    """Detect a byte sample's text encoding.

    Args:
        sample: A bounded byte sample from the start of the source file
            (the ``tests/fixtures/corpus.yaml``-documented ~64 KiB
            convention -- never the whole file; charset-normalizer's cost is
            only bounded because callers respect this, per this module's own
            threat-model note in 06-04-PLAN.md).
        contract_encoding: A dataset contract's declared encoding
            (``CsvParsingConfig.encoding``), or ``None`` to run detection.
            When set, detection never runs at all.
        min_confidence: The minimum charset-normalizer-derived confidence a
            detected (non-BOM, non-contract) result must reach to be
            reported as ``source="detected"`` rather than
            ``source="undetermined"``. Defaults to
            ``DEFAULT_MIN_CONFIDENCE``.

    Returns:
        The detection result. Never raises -- an undecodable or ambiguous
        sample is reported as ``source="undetermined"``, not an exception;
        ``decode_strict`` is the function that raises, once a caller has
        chosen an encoding to actually decode with.
    """
    if contract_encoding is not None:
        return EncodingDetection(contract_encoding, 1.0, "contract")
    for bom, name in _BOM_TABLE:
        if sample.startswith(bom):
            return EncodingDetection(name, 1.0, "bom")

    candidates = from_bytes(sample)
    cn_best = candidates.best()
    cd = chardet.detect(sample)
    if cn_best is None or cd["encoding"] is None:
        return EncodingDetection("undetermined", 0.0, "undetermined")

    cd_name = codecs.lookup(cd["encoding"]).name
    match = _best_corroborating_match(candidates, cn_best, cd_name)
    if match is None:
        return EncodingDetection("undetermined", 0.0, "undetermined")

    return _classify_match(match, sample, min_confidence=min_confidence)


def _best_corroborating_match(
    candidates: CharsetMatches, cn_best: CharsetMatch, cd_name: str
) -> CharsetMatch | None:
    """Return the charset-normalizer candidate that corroborates chardet's guess, if any.

    charset-normalizer's own top pick agrees when its canonicalized name
    already equals chardet's. When it does not, a candidate within
    ``_NEAR_TIE_CHAOS_EPSILON`` of the best chaos is checked too --
    ``candidates`` iterates in ascending-chaos order (charset-normalizer's
    own sort, verified against its source), so the loop stops the moment a
    candidate's chaos exceeds that margin.

    Args:
        candidates: Every candidate charset-normalizer considered, best
            (lowest chaos) first.
        cn_best: ``candidates.best()`` -- charset-normalizer's own top pick.
        cd_name: chardet's canonicalized encoding name.

    Returns:
        The corroborating match (``cn_best`` itself, or a near-tie), or
        ``None`` if no candidate within the epsilon names ``cd_name``.
    """
    best_name = codecs.lookup(cn_best.encoding).name
    if best_name == cd_name:
        return cn_best
    for candidate in candidates:
        if candidate.chaos - cn_best.chaos > _NEAR_TIE_CHAOS_EPSILON:
            break
        if codecs.lookup(candidate.encoding).name == cd_name:
            return candidate
    return None


def _classify_match(
    match: CharsetMatch, sample: bytes, *, min_confidence: float
) -> EncodingDetection:
    """Turn a corroborated candidate into a reported detection.

    Args:
        match: The corroborated charset-normalizer candidate.
        sample: The original byte sample, re-examined for the no-BOM
            wide-encoding confidence ceiling.
        min_confidence: The threshold below which the result is reported as
            ``source="undetermined"`` rather than ``source="detected"``.

    Returns:
        The classified detection, with the confidence ceiling applied
        before the ``min_confidence`` comparison.
    """
    name = codecs.lookup(match.encoding).name
    confidence = round(1.0 - match.chaos, 4)
    if _looks_like_unmarked_wide_encoding(sample):
        confidence = min(confidence, _NO_BOM_CONFIDENCE_CEILING)
    if confidence < min_confidence:
        return EncodingDetection(name, confidence, "undetermined")
    return EncodingDetection(name, confidence, "detected")


def _looks_like_unmarked_wide_encoding(sample: bytes) -> bool:
    """Return whether more than ``_WIDE_CHAR_NUL_RATIO_THRESHOLD`` of ``sample`` is NUL bytes.

    Args:
        sample: The byte sample being classified.

    Returns:
        Whether the NUL-byte ratio crosses the threshold. Always ``False``
        for an empty sample.
    """
    if not sample:
        return False
    return (sample.count(0) / len(sample)) > _WIDE_CHAR_NUL_RATIO_THRESHOLD


def decode_strict(sample: bytes, detection: EncodingDetection) -> str:
    """Decode ``sample`` with ``detection.encoding``, raising on any invalid byte.

    Proves the corpus's own stated policy: "the reader must declare
    strict/replace/surrogateescape... the default (strict) raises, so the
    choice cannot be made by accident" -- ``errors="strict"`` is used
    unconditionally here; a configurable error-handling mode is not this
    plan's concern.

    Args:
        sample: The raw bytes to decode.
        detection: A prior ``detect_encoding`` result naming the encoding to
            decode with.

    Returns:
        The decoded text.

    Raises:
        EncodingDetectionError: ``sample`` contains a byte sequence that is
            not valid under ``detection.encoding``.
    """
    try:
        return sample.decode(detection.encoding, errors="strict")
    except UnicodeDecodeError as exc:
        msg = f"cannot decode sample as {detection.encoding!r}: {exc}"
        raise EncodingDetectionError(
            msg,
            context={"diagnostic_code": "undecodable-bytes", "encoding": detection.encoding},
        ) from exc
